--suppliers
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Tagfeed', '3273 Lunder Crossing', '738-423-2102', 'jchant0@nih.gov', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Mymm', '55549 Schurz Junction', '187-862-8338', 'mbroe1@github.com', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Meedoo', '2222 Monterey Hill', '480-430-4805', 'rdanzig2@ox.ac.uk', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Brainsphere', '96 Cordelia Avenue', '167-913-0262', 'ckindall3@cisco.com', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Skynoodle', '048 Daystar Trail', '325-448-1649', 'rphythian4@google.de', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Skaboo', '763 Luster Road', '319-591-7527', 'sspelman5@state.gov', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Twinte', '6175 Prairieview Place', '129-755-0478', 'anangle6@wired.com', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Jayo', '135 Washington Terrace', '619-320-7438', 'jkopecka7@parallels.com', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Dabfeed', '2197 Eastlawn Park', '419-543-0428', 'gheyworth8@engadget.com', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Devify', '368 Sundown Road', '785-771-5761', 'lbeven9@furl.net', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Thoughtstorm', '608 Summer Ridge Center', '773-618-2253', 'efroomea@gmpg.org', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Devcast', '69149 Randy Court', '373-409-3360', 'eraffertyb@reference.com', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Lazz', '09298 Eggendart Road', '129-283-8051', 'tgrishaginc@accuweather.com', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Camimbo', '86 Bobwhite Street', '658-105-7827', 'kcoolsond@engadget.com', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Dablist', '535 3rd Court', '364-885-9894', 'dmionie@smh.com.au', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Skaboo', '880 Goodland Lane', '398-508-1424', 'esnelgarf@jigsy.com', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Eazzy', '5732 Lukken Pass', '306-460-3115', 'rsymeg@hubpages.com', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Skiptube', '8845 Chive Street', '980-685-6469', 'rbirkbeckh@prweb.com', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Skalith', '5 Sachtjen Street', '544-556-3357', 'estandrini@spiegel.de', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('JumpXS', '4 Northland Pass', '344-680-6131', 'imarcumj@twitpic.com', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Youtags', '0019 Graceland Point', '199-924-0009', 'sbaileyk@china.com.cn', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Dynazzy', '43 Katie Junction', '426-983-2361', 'sbevesl@infoseek.co.jp', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Thoughtmix', '8 Hansons Way', '417-188-9490', 'bgowansm@earthlink.net', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Gigashots', '19221 Village Green Lane', '980-268-5636', 'chackeyn@marriott.com', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Demimbu', '3057 Erie Place', '290-746-8533', 'abrauno@hexun.com', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Meezzy', '49 Village Green Way', '237-238-3618', 'scayp@msn.com', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Tazzy', '51697 Springs Trail', '259-858-5764', 'tromagnosiq@cnn.com', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Oyope', '93 Gale Place', '870-769-5009', 'wdorier@cpanel.net', 0, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Voonder', '22798 Becker Crossing', '482-445-8295', 'labarrows@globo.com', 1, 'Supplier');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Browsebug', '1228 Susan Lane', '372-379-7378', 'jfoyt@shutterfly.com', 0, 'Supplier');
--Buyers
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Katz', '4 Marquette Junction', '326-938-4681', 'ddinan0@mozilla.org', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Dynava', '64117 Dovetail Drive', '638-704-3464', 'gbaddam1@posterous.com', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Yombu', '6 Lakewood Parkway', '600-560-5530', 'zgerren2@blogs.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Skinte', '9227 David Road', '980-827-8933', 'rloidl3@google.com.br', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Voonte', '572 Prairie Rose Parkway', '455-927-9197', 'qjeeks4@issuu.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Nlounge', '6723 Mallard Drive', '546-667-2721', 'boylett5@imageshack.us', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Devcast', '6 Lukken Plaza', '199-449-5094', 'ngorgen6@chicagotribune.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Lajo', '46 New Castle Pass', '634-518-0803', 'atalbot7@elpais.com', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Feedmix', '08846 Maryland Alley', '204-961-5017', 'nbillinge8@domainmarket.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Leexo', '2 Messerschmidt Avenue', '149-369-2019', 'bgreenset9@github.com', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Gabtune', '64394 Ridgeview Alley', '572-307-4828', 'mbromella@ucoz.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Flipopia', '67 Mandrake Alley', '258-676-0384', 'gshinnb@wix.com', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Leexo', '6541 Morrow Alley', '914-936-8853', 'kdoolanc@com.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Eire', '1225 Johnson Road', '591-581-8936', 'fegand@51.la', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Teklist', '4545 Stuart Plaza', '470-804-4645', 'fchealee@icq.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Centidel', '383 Golf Alley', '469-445-7455', 'ttrankf@mayoclinic.com', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Dynabox', '3 Colorado Hill', '899-726-0787', 'olegging@europa.eu', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Kayveo', '225 Steensland Park', '965-603-8100', 'kdoddh@homestead.com', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Centimia', '7 Cardinal Alley', '949-652-9607', 'mbissekeri@mail.ru', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Voonyx', '48 Old Gate Avenue', '963-516-1129', 'mdecortj@fema.gov', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Wikibox', '01 Browning Drive', '722-733-1794', 'lbradnumk@omniture.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Tanoodle', '4727 Helena Parkway', '587-221-0063', 'obatchanl@reverbnation.com', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Bubblemix', '33 Nova Place', '898-676-9073', 'awheelikerm@ycombinator.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Blogtags', '4161 International Junction', '248-595-8531', 'kmarklinn@comcast.net', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Skimia', '0 Packers Lane', '292-586-9965', 'mtwentymano@arstechnica.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Jabbercube', '70877 Oakridge Place', '651-996-9331', 'ggookp@psu.edu', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Fliptune', '8200 Laurel Court', '369-885-5634', 'rkellochq@webmd.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Livepath', '37555 Cordelia Avenue', '118-876-8927', 'hfullertonr@umich.edu', 0, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Topicshots', '91541 Ronald Regan Junction', '280-291-2497', 'rfahys@youku.com', 1, 'Buyer');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Yodoo', '60048 Parkside Road', '228-900-2877', 'agodferyt@upenn.edu', 0, 'Buyer');
--Employees
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Teklist', '44 Luster Terrace', '638-578-9686', 'rsitch0@goo.gl', 1, 'Employee');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Realfire', '0 Superior Hill', '103-671-4083', 'kguerrero1@walmart.com', 0, 'Employee');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Yodel', '0097 Karstens Road', '809-347-0521', 'gpetrushka2@china.com.cn', 1, 'Employee');
--Vendors
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Zoonoodle', '39756 Dawn Avenue', '572-965-2316', 'ccookney0@spotify.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Eare', '882 Roxbury Park', '864-153-8294', 'erennicks1@instagram.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Yambee', '9 American Ash Alley', '483-272-4207', 'jenga2@ustream.tv', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Gabtune', '269 Division Center', '994-694-2433', 'mfarnan3@goo.gl', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Photobean', '753 Acker Circle', '510-316-1849', 'csteward4@businessweek.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Shuffledrive', '369 Straubel Hill', '817-337-1707', 'abygrave5@indiatimes.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Leenti', '79 Duke Pass', '699-884-9184', 'iakam6@bizjournals.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Jayo', '7 Kings Trail', '690-257-9272', 'drallings7@jugem.jp', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Photofeed', '2 Transport Way', '848-258-7806', 'bwhether8@redcross.org', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Oodoo', '7522 Hermina Drive', '451-896-8102', 'jharford9@so-net.ne.jp', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Meembee', '3 Heath Pass', '969-963-3050', 'rtwinbornea@feedburner.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Skidoo', '9040 Sycamore Road', '264-514-8443', 'wshyreb@behance.net', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Twitterwire', '839 Raven Junction', '342-515-5335', 'lmatyasikc@bbc.co.uk', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Aimbo', '312 Warner Crossing', '499-777-0258', 'gabberleyd@printfriendly.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Edgeblab', '763 Debs Park', '630-170-2840', 'cstonemane@blogs.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Voolith', '993 Macpherson Plaza', '136-113-6806', 'eloddyf@gravatar.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Eare', '909 Hintze Park', '653-256-8851', 'djakubowiczg@about.me', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Digitube', '12 Stang Court', '622-582-5213', 'jluetyh@vk.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Devcast', '51875 Delaware Junction', '927-573-8012', 'ddunsmuiri@dell.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Demizz', '799 Maryland Pass', '168-185-8003', 'zbindonj@fotki.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Vimbo', '6875 Myrtle Road', '949-299-6134', 'mlytllek@tripod.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Jetpulse', '308 Reindahl Street', '413-230-8080', 'dwydl@flavors.me', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Lazzy', '165 Warrior Trail', '857-567-1258', 'mhaselgrovem@nih.gov', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Aibox', '163 Parkside Alley', '660-430-2531', 'hhaddickn@buzzfeed.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Gabspot', '19 Prairie Rose Crossing', '106-372-4928', 'rhumberstono@goodreads.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Shuffletag', '2 Derek Court', '809-342-8302', 'wwharinp@mediafire.com', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Zoomdog', '4 Sunfield Way', '907-441-4989', 'mduggetq@mapy.cz', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Thoughtbeat', '6 Straubel Pass', '263-951-5387', 'ckynsonr@google.cn', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Tagcat', '55 Butternut Center', '166-737-0027', 'rwarens@webeden.co.uk', 1, 'Vendor');
insert into Parties (P_Name, Address, Phone, Email, Status, [Group]) values ('Digitube', '6 Burning Wood Place', '223-808-6068', 'dantushevt@reference.com', 1, 'Vendor');

Select * from Parties
--Stock
insert into [Stock] ( [itemDetail], [Price], [Group], [ItemStatus], [Quantity],[Packing],[UpdatedBy],[UpdatedDate]) values ('14oz B/PATA 72 inch', 4000, 'Cloth', 1, 200, 'ROLL', 'Admin', '2020-08-25 13:36:47');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('20 oz 60 inch (w)', 8000, 'Cloth', 1, 2005, 'Meter', 'Admin', '2020-08-11 15:57:33');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('2m (w)26 0z ', 1800, 'Cloth', 1, 2000, 'Meter', 'Admin', '2020-08-18 14:05:36');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('42" full black  14 oz', 5600, 'Cloth', 1, 2011, 'Meter', 'Admin', '2020-12-20 17:16:42');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('42"full black 21 oz', 8800, 'Cloth', 1, 2010, 'Meter', 'Admin', '2020-08-31 16:30:36');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('73" B/patta 21 oz', 9100, 'Cloth', 1, 2009, 'Meter', 'Admin', '2020-11-26 04:42:19');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('42" white 14 oz', 2600, 'Cloth', 1, 1992, 'Meter', 'Admin', '2020-10-08 22:34:45');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('42" white 21 oz', 4200, 'Cloth', 1, 1995, 'Meter', 'Admin', '2021-03-17 22:27:09');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('42" white 11 oz', 7300, 'Cloth', 1, 1994, 'Meter', 'Admin', '2021-02-27 03:08:51');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('37" white 10 oz', 2200, 'Cloth', 1, 2010, 'Meter', 'Admin', '2020-10-06 06:11:46');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('35" white 9 0z Tarpaal', 4400, 'Cloth', 1, 1987, 'Meter', 'Admin', '2021-02-01 03:57:58');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('42" white 16 oz', 1000, 'Cloth', 1, 2012, 'Meter', 'Admin', '2021-02-08 21:15:35');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('42" w/proof ', 10000, 'Cloth', 1, 2003, 'Meter', 'Admin', '2021-05-02 06:40:26');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('2" white', 12152, 'Nawar', 1, 1996, 'Bag', 'Admin', '2020-12-16 23:43:40');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('2.5" white', 3823, 'Nawar', 1, 1992, 'Bag', 'Admin', '2020-07-02 04:32:12');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('3" white', 2038, 'Nawar', 1, 1988, 'Bag', 'Admin', '2021-02-07 08:22:04');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('2" Gray', 13081, 'Nawar', 1, 2006, 'Bag', 'Admin', '2021-01-05 12:13:38');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('2.5" Gray', 8434, 'Nawar', 1, 2008, 'Bag', 'Admin', '2021-05-17 02:17:05');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('3" Gray', 6278, 'Nawar', 1, 1988, 'Bag', 'Admin', '2021-01-28 18:16:42');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('1.5" white', 7841, 'Rope', 1, 2008, 'Meter', 'Admin', '2020-08-31 16:42:12');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('1" white', 5295, 'Rope', 1, 1994, 'Meter', 'Admin', '2020-07-07 01:28:13');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('10mm white', 10869, 'Rope', 1, 1995, 'Meter', 'Admin', '2021-03-30 20:07:17');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('1.5" Gray', 3809, 'Rope', 1, 2003, 'Meter', 'Admin', '2021-03-12 16:58:03');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('1" Gray', 14523, 'Rope', 1, 1993, 'Meter', 'Admin', '2021-03-19 18:39:32');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('10mm Gray', 9553, 'Rope', 1, 2005, 'Meter', 'Admin', '2020-08-02 03:39:46');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('white', 7841, 'Phali dori', 1, 2008, 'Meter', 'Admin', '2020-08-31 16:42:12');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Gray', 5295, 'Phali dori', 1, 1994, 'Meter', 'Admin', '2020-07-07 01:28:13');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Big', 10869, 'D', 1, 1995, 'Meter', 'Admin', '2021-03-30 20:07:17');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Small" Gray', 3809, 'D', 1, 2003, 'Meter', 'Admin', '2021-03-12 16:58:03');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Big', 14523, 'Rendis', 1, 1993, 'Meter', 'Admin', '2021-03-19 18:39:32');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Small', 9553, 'Rendis', 1, 2005, 'Meter', 'Admin', '2020-08-02 03:39:46');

insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('KDM', 7841, 'Ring', 1, 2008, 'Meter', 'Admin', '2020-08-31 16:42:12');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('135 gsm', 5295, 'Print', 1, 1994, 'Pound', 'Admin', '2020-07-07 01:28:13');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('120 gsm', 10869, 'Print', 1, 1995, 'Pound', 'Admin', '2021-03-30 20:07:17');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('80 gsm', 3809, 'Print', 1, 2003, 'Pound', 'Admin', '2021-03-12 16:58:03');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Big', 14523, 'Thippa', 1, 1993, 'Piece', 'Admin', '2021-03-19 18:39:32');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Small', 9553, 'Thippa', 1, 2005, 'Piece', 'Admin', '2020-08-02 03:39:46');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Convention ', 13141, 'Yarn', 1, 1992, 'Meter', 'Admin', '2021-03-06 18:45:32');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Black single 10/1', 1360, 'Yarn', 1, 1999, 'Meter', 'Admin', '2021-06-04 17:45:08');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Black double 10/2', 7354, 'Yarn', 1, 1995, 'Meter', 'Admin', '2021-03-28 23:46:20');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Black trpple10/3', 3316, 'Yarn', 1, 2009, 'Meter', 'Admin', '2020-08-03 03:04:59');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Red single 10/1', 12458, 'Yarn', 1, 1996, 'Meter', 'Admin', '2021-03-24 10:21:35');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Red double 10/2', 14814, 'Yarn', 1, 1988, 'Meter', 'Admin', '2021-05-08 02:48:06');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Gray single 10/1', 10420, 'Yarn', 1, 1988, 'Meter', 'Admin', '2020-06-23 15:37:08');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Gray double 10/2', 1069, 'Yarn', 1, 2006, 'Meter', 'Admin', '2021-02-07 18:19:37');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('White single 8/1', 1069, 'Yarn', 1, 2006, 'Meter', 'Admin', '2021-02-07 18:19:37');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('White single 10/1', 1069, 'Yarn', 1, 2006, 'Meter', 'Admin', '2021-02-07 18:19:37');

insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('White double 10/2', 1069, 'Yarn', 1, 2006, 'Meter', 'Admin', '2021-02-07 18:19:37');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('White tripple 10/3', 1069, 'Yarn', 1, 2006, 'Meter', 'Admin', '2021-02-07 18:19:37');
--ProductsInStock
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Canvas Tent Black', 9404, 'Yarn', 1, 0, 'Piece', 'Admin', '2021-02-07 18:19:37');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Double Fly single Fold Tent', 12022, 'Yarn', 1, 0, 'Piece', 'Admin', '2021-02-07 18:19:37');

insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Double Fly Double Fold Tent', 15044, 'Yarn', 1, 0, 'Piece', 'Admin', '2021-02-07 18:19:37');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Army Frame Tent', 30938, 'Yarn', 1, 0, 'Piece', 'Admin', '2021-02-07 18:19:37');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('African Refugee Tent', 14910, 'Yarn', 1, 0, 'Meter', 'Piece', '2021-02-07 18:19:37');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Blue and White Deluxe Tent', 31828, 'Yarn', 1, 0, 'Piece', 'Admin', '2021-02-07 18:19:37');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Canvas Drop Cloth', 30237 , 'Yarn', 1, 0, 'Piece', 'Admin', '2021-02-07 18:19:37');

insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('General Purpose Tent', 41036, 'Yarn', 1, 0, 'Piece', 'Admin', '2021-02-07 18:19:37');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Bath Towel', 12715, 'Yarn', 1, 0, 'Piece', 'Admin', '2021-02-07 18:19:37');
insert into [Stock] ([itemDetail], [Price], [Group], [ItemStatus], [Quantity], [Packing], [UpdatedBy], [UpdatedDate] ) values ('Bell Tent', 29618, 'Yarn', 1, 0, 'Piece', 'Admin', '2021-02-07 18:19:37');

select * from Stock

--Products
insert into [Product] (Description, P_Price) values ('Canvas Tent Black', 9404);
insert into [Product] (Description, P_Price) values ('Double Fly single Fold Tent', 12022);
insert into [Product] (Description, P_Price) values ('Double Fly Double Fold Tent', 15044);
insert into [Product] (Description, P_Price) values ('Army Frame Tent', 30938);
insert into [Product] (Description, P_Price) values ('African Refugee Tent', 14910);
insert into [Product] (Description, P_Price) values ('Blue and White Deluxe Tent	', 31828);
insert into [Product] (Description, P_Price) values ('Canvas Drop Cloth', 30237);
insert into [Product] (Description, P_Price) values ('General Purpose Tent', 41036);
insert into [Product] (Description, P_Price) values ('Bath Towel', 12715);
insert into [Product] (Description, P_Price) values ('Bell Tent', 29618);

Select * from Product


--ProductDetails
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 31, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 12, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 14, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 40, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 27, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 6, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 38, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 38, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 15, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 45, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 12, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 21, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 31, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 17, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 41, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 37, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 18, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 32, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 30, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 14, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 34, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 45, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 41, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 33, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 37, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 47, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 21, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 24, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 9, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 10, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 46, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 7, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 26, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 16, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 17, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 27, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 16, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 14, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 1, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 8, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 3, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 6, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 47, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 19, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 5, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 13, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 36, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 16, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 41, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 20, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 8, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 42, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 46, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 18, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 7, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 9, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 13, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 10, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 32, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 47, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 34, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 13, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 2, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 45, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 18, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 22, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 6, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 7, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 30, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 44, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 10, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 46, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 32, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 16, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 18, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 36, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 5, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 16, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 37, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 23, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 12, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 37, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 12, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 11, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 20, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 48, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 11, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 7, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 4, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 4, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 25, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 9, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 36, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 35, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 44, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 39, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 41, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 23, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 11, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 34, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 49, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 34, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 35, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 44, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 22, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 33, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 4, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 23, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 13, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 15, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 28, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 9, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 49, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 23, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 9, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 12, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 17, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 18, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 47, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 9, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 3, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 9, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 2, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 39, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 1, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 26, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 10, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 19, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 3, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 41, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 7, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 27, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 11, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 29, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 1, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 44, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 6, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 4, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 48, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 49, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 36, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 8, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 5, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 23, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 22, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 36, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 32, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 25, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 49, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 18, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 21, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 11, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 1, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 32, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 12, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 34, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 12, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 7, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 28, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 42, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 30, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 9, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 17, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 35, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 31, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 11, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 18, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 44, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 11, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 11, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 2, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 9, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 2, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 25, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 26, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 36, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 49, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 45, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 27, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 35, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 45, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 32, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 45, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 19, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 43, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 16, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 43, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 32, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 8, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 18, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 46, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 10, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 42, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 7, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 30, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 31, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 16, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 36, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 42, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 3, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 15, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 41, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 43, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 21, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 15, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 4, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 23, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 46, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 13, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 20, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 30, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 41, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 16, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 38, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 19, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 49, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 41, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 21, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 45, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 25, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 18, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 33, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 4, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 2, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 49, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 41, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 29, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 26, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 7, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 43, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 36, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 45, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 45, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 44, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 3, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 27, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 2, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 43, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 41, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 26, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 11, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 10, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 14, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 37, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 17, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 30, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 8, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 31, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 18, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 11, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 40, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 3, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 42, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 21, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 24, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 23, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 19, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 29, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 24, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 15, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 9, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 28, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 26, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 48, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 14, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 36, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 21, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 1, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 34, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 40, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 1, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 40, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 29, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (8, 33, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 11, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 41, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 32, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 12, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 47, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 35, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 7, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 28, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 26, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 10, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (7, 47, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (6, 35, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 39, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 6, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (4, 40, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (5, 37, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 35, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 26, 1);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (3, 44, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 5, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 11, 5);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (10, 46, 2);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 48, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (9, 35, 3);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (1, 40, 4);
insert into [ProductDetails] (ProductID, ItemID, Quantity) values (2, 3, 4);


------------Orders---------------------------
EXEC CreateNewOrder @PartiesID = 34,@ProductID = 3, @quantity = 222;
EXEC CreateNewOrder @PartiesID = 35,@ProductID = 4, @quantity = 235;
EXEC CreateNewOrder @PartiesID = 36,@ProductID = 5, @quantity = 227;
EXEC CreateNewOrder @PartiesID = 37,@ProductID = 6, @quantity = 269;
EXEC CreateNewOrder @PartiesID = 38,@ProductID = 7, @quantity = 278;
EXEC CreateNewOrder @PartiesID = 39,@ProductID = 8, @quantity = 298;

EXEC CreateNewOrder @PartiesID = 45,@ProductID = 5, @quantity = 2;
EXEC CreateNewOrder @PartiesID = 31,@ProductID = 5, @quantity = 456;
EXEC CreateNewOrder @PartiesID = 32,@ProductID = 5, @quantity = 342;
EXEC CreateNewOrder @PartiesID = 33,@ProductID = 5, @quantity = 562;
EXEC CreateNewOrder @PartiesID = 34,@ProductID = 5, @quantity = 762;
EXEC CreateNewOrder @PartiesID = 35,@ProductID = 3, @quantity = 902;
EXEC CreateNewOrder @PartiesID = 31,@ProductID = 9, @quantity = 122;
EXEC CreateNewOrder @PartiesID = 32,@ProductID = 2, @quantity = 382;
EXEC CreateNewOrder @PartiesID = 33,@ProductID = 2, @quantity = 392;
EXEC CreateNewOrder @PartiesID = 34,@ProductID = 2, @quantity = 452;
EXEC CreateNewOrder @PartiesID = 35,@ProductID = 2, @quantity = 762;

----------------------------PurchaseInvoice----------------------
EXEC PPURCHASE_INVOICE @PartiesID = 1,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 2;
EXEC PPURCHASE_INVOICE @PartiesID = 2,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 4;
EXEC PPURCHASE_INVOICE @PartiesID = 3,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 5;
EXEC PPURCHASE_INVOICE @PartiesID = 4,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 6;
EXEC PPURCHASE_INVOICE @PartiesID = 5,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 7;
EXEC PPURCHASE_INVOICE @PartiesID = 6,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 8;
EXEC PPURCHASE_INVOICE @PartiesID = 7,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 9;
EXEC PPURCHASE_INVOICE @PartiesID = 8,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 10;
EXEC PPURCHASE_INVOICE @PartiesID = 9,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 11;
EXEC PPURCHASE_INVOICE @PartiesID = 10,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 12;
EXEC PPURCHASE_INVOICE @PartiesID = 11,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 13;
EXEC PPURCHASE_INVOICE @PartiesID = 1,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 14;
EXEC PPURCHASE_INVOICE @PartiesID = 2,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 15;
EXEC PPURCHASE_INVOICE @PartiesID = 3,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 16;
EXEC PPURCHASE_INVOICE @PartiesID = 4,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 17;
EXEC PPURCHASE_INVOICE @PartiesID = 4,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 18;
EXEC PPURCHASE_INVOICE @PartiesID = 5,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 19;
EXEC PPURCHASE_INVOICE @PartiesID = 5,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@OrderID = 20;


----------------------------Purchase details------------------------------
EXEC Purchase_Details_input @InvoiceNo = 2, @ItemID = 5, @Rate = 9000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 4, @ItemID = 6, @Rate = 6000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 5, @ItemID = 7, @Rate = 4000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 6, @ItemID = 8, @Rate = 3000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 7, @ItemID = 9, @Rate = 2000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 8, @ItemID = 10, @Rate = 1000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 9, @ItemID = 11, @Rate = 9000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 10, @ItemID = 12, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 11, @ItemID = 13, @Rate = 7000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 12, @ItemID = 14, @Rate = 6000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 13, @ItemID = 15, @Rate = 5000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 14, @ItemID = 16, @Rate = 4000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 15, @ItemID = 17, @Rate = 3000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 16, @ItemID = 18, @Rate = 2000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 17, @ItemID = 19, @Rate = 3000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 18, @ItemID = 20, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 19, @ItemID = 21, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 20, @ItemID = 22, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 2, @ItemID = 23, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 3, @ItemID = 24, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 4, @ItemID = 25, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 5, @ItemID = 26, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 6, @ItemID = 27, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 7, @ItemID = 28, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 8, @ItemID = 29, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 9, @ItemID = 30, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 10, @ItemID = 31, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 11, @ItemID = 32, @Rate = 8000, @Quantity = 120;
EXEC Purchase_Details_input @InvoiceNo = 12, @ItemID = 33, @Rate = 8000, @Quantity = 120;



---------------------------Gatepass Out Head---------------------------------
EXEC GATEPassOUT_Proc @PartiesID = 65,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 70000,@OrderID = 2,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 66,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 10000,@OrderID = 4,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 67,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 20000,@OrderID = 5,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 68,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 30000,@OrderID = 6,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 69,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 40000,@OrderID = 7,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 70,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 50000,@OrderID = 8,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 71,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 60000,@OrderID = 9,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 72,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 70000,@OrderID = 10,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 73,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 80000,@OrderID = 11,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 74,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 90000,@OrderID = 12,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 75,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 100000,@OrderID = 13,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 76,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 70000,@OrderID = 14,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 77,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 30000,@OrderID = 15,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 78,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 40000,@OrderID = 16,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 79,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 50000,@OrderID = 17,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 80,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 60000,@OrderID = 18,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 81,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 80000,@OrderID = 19,@Remarks = 'MadeBySahaheer';
EXEC GATEPassOUT_Proc @PartiesID = 82,@Details = 'MadeByShaheer',@Reference ='1-11-1111',@AmountPaid = 90000,@OrderID = 20,@Remarks = 'MadeBySahaheer';


---------------------------------------gate pass out Details-----------------------
EXEC GatePassOUT_Details  @InvoiceNo = 2, @ItemID = 1, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 3, @ItemID = 2, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 4, @ItemID = 4, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 5, @ItemID = 5, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 6, @ItemID = 6, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 7, @ItemID = 7, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 8, @ItemID = 8, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 9, @ItemID = 9, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 10, @ItemID = 10, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 11, @ItemID = 11, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 12, @ItemID = 12, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 13, @ItemID = 13, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 14, @ItemID = 14, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 15, @ItemID = 1, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 16, @ItemID = 2, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 17, @ItemID = 3, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 18, @ItemID = 4, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 19, @ItemID = 5, @Quantity = 10;
EXEC GatePassOUT_Details  @InvoiceNo = 20, @ItemID = 6, @Quantity = 10;


-----------------------------Cash Payment------------------------------
EXEC CashPayment_Invoice @voucherID = 1002 ,@PartiesID = 1, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1003 ,@PartiesID = 2, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1004 ,@PartiesID = 3, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1005 ,@PartiesID = 4, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1006 ,@PartiesID = 5, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1007 ,@PartiesID = 6, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1008 ,@PartiesID = 7, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1009 ,@PartiesID = 8, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1010 ,@PartiesID = 9, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1011 ,@PartiesID = 20, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1012 ,@PartiesID = 21, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1013 ,@PartiesID = 22, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1014 ,@PartiesID = 23, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';
EXEC CashPayment_Invoice @voucherID = 1015 ,@PartiesID = 24, @Amount = 19000, @Reference ='deleteme',@details = 'MadeByShaheer';




----------------------------Sales -------------------------------------------
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 2,@Remarks = 'ByShaheer', @amount = 2000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 3,@Remarks = 'ByShaheer', @amount = 3000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 4,@Remarks = 'ByShaheer', @amount = 4000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 5,@Remarks = 'ByShaheer', @amount = 5000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 6,@Remarks = 'ByShaheer', @amount = 6000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 7,@Remarks = 'ByShaheer', @amount = 7000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 8,@Remarks = 'ByShaheer', @amount = 8000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 9,@Remarks = 'ByShaheer', @amount = 9000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 10,@Remarks = 'ByShaheer', @amount = 1000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 11,@Remarks = 'ByShaheer', @amount = 2000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 12,@Remarks = 'ByShaheer', @amount = 3000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 13,@Remarks = 'ByShaheer', @amount = 4000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 14,@Remarks = 'ByShaheer', @amount = 6000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 15,@Remarks = 'ByShaheer', @amount = 5000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 16,@Remarks = 'ByShaheer', @amount = 7000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 17,@Remarks = 'ByShaheer', @amount = 8000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 18,@Remarks = 'ByShaheer', @amount = 9000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 19,@Remarks = 'ByShaheer', @amount = 5000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
EXEC SALES_Invoice @Details = 'ByShaheer', @Reference = '11-111-11', @OrderID = 20,@Remarks = 'ByShaheer', @amount = 4000000, @Description = 'MadeByShaheer', @shipAmount = 90000;
